# Generated by Django 2.2 on 2019-04-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('code', models.FloatField(unique=True)),
                ('ingredient1', models.CharField(max_length=50)),
                ('ingredient2', models.CharField(max_length=50, null=True)),
                ('temperature', models.CharField(max_length=50)),
                ('climate', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('emotion', models.CharField(max_length=50)),
            ],
        ),
    ]
