# Generated by Django 2.2 on 2019-04-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Post_blog',
        ),
    ]
